version: "3.8"

services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/local/src/app
    environment:
      NUXT_HOST: 0.0.0.0

  backend:
    build:
      context: backend
    ports:
      - "1323:1323"

